title: Club Penguin Again Status
languageCode: en
params:
  copyrightHolder: Club Penguin Again
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>Example.com</a> provides open-source
    software for all kind of sectors.
  description_header: >-
    Information regarding the status of <a class='text-grey-darkest' title='Club
    Penguin Again' href='https://clubpenguinagain.com/'>Club Penguin
    Again</a>.<br />Follow us <a class='text-grey-darkest' title='Visit our
    Twitter href='https://www.twitter.com/CPAgain'>on Twitter</a> or subscribe
    to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events and updates.
  eventsPerPage: 10
  groups:
    - Site
    - Game
    - Support
  logo: /var/www/html/Logo.png
  meta_description: Information regarding the status of Club Penguin Again.
  shortDateFormat: 'Jan 2 â€” 15:04'
  systems:
    - description: 'Our Website including the Homepage, Blog and Help pages.'
      link: 'https://clubpenguinagain.com/'
      name: Website
    - description: >-
        Cloudflare is one of our DDoS protection and DNS providers, they proxy
        all of our traffic through their network.
      link: ''
      name: Cloudflare
    - description: Servers responsible for running the game.
      link: 'https://clubpenguinagain.com/play/'
      name: Game Servers
    - description: Servers responsible for login's.
      link: 'https://clubpenguinagain.com/play'
      name: Login Servers
    - description: Servers responsible for Unlock items.
      name: Redemption Server
    - description: Server responsible for sending and receiving emails to the Support Team.
      name: Support Email Server
    - description: >-
        Hosted by LiveSupporti - allows users to create tickets and live chat to
        our Support team.
      name: Live Chat
  timezoneString: ' GMT'
